### ISSUE TITLE
Incredible work!!

### ISSUE THREAD

**Issue by pha-nguyen** [vuthede/speech_separation_PIT#1]
Congratulations, very well-deserved! Please file a patent base on this work.

**Comment by vuthede** [comment]
Oh come on man, just a runnable version. You should file patent to your best CVPR  too

**Comment by pha-nguyen** [comment]
Hi bra, please write up a disclosure form for the patent and send me by Monday, thanks! :)

**Comment by vuthede** [comment]
Oh come on man, now is Monday already. Good luck bra. :))
